name: SuperTrailsPro
version: v1.2.15
main: me.kvq.supertrailspro.SuperTrailsPro
author: [kvq]
loadbefore: [SuperTrails]
softdepend: [Citizens]
commands:
  trails:
    description: null
  supertrails:
    description: null
  trailsid:
    description: null